### ISSUE TITLE
想咨询下透传消息的内容

### ISSUE THREAD

**Issue by xishuango0o0** [GetuiLaboratory/cordova-plugin-getuisdk#1]
dear:
目前正在研究并使用这个个推SDK，但是使用透传消息时遇到点问题。
透传消息的js callback方法在APP关闭后就算接收到也不能处理，想问问看有木有什么好的实现思路？

除了更改GeTuiSdkPushReceiver以外...

**Comment by BigMuGe** [comment]
1.可以自定义一个Service,在GeTuiSdkPushReceiver中识别应用退出的情况下发送透传数据给service去做处理
2.可以在GeTuiSdkPushReceiver中将接到的透传数据存到本地db，等下次应用打开的时候再做处理

仅供参考，希望有所帮助

**Comment by xishuango0o0** [comment]
@BigMuGe 
首先非常感谢您的回复！
谢谢您了，因为我不是很懂android代码，所以实现起来有些困难，看来只能借助同学帮忙了。
不过我还是把我想到的实现思路简单说下，

1. 插件来实现这个Service，定义一个private的字典对象，

1. Service实现一些比较常用的消息操作，比如play sound、push local notify等等
    _目前只能想到这些，（无耻点因为我只用到这点^_^）当然还有其他_

1. 应用启动时，由JS来往字典中插入对应透传消息内容的操作，内容即Key，操作即Value，
   
    _当然对透传消息格式有要求，鉴于这个原因可能会影响插件的通用性_
   操作以数组的方式存JSON格式，如play sound 需要指定音频路径，发送本地通知需要指定title，content等等本地通知需要的字段。

1. 当客户端service收到消息时，service去解析字典，然后一个一个执行即可。

_上述纯属自己意淫，解决了JS同学不懂Android代码的痛。我这么跟同学讲的，还不知道能能不能帮忙实现._
