### ISSUE TITLE
ionic 从哪里 import GetuiSdkPlugin?

### ISSUE THREAD

**Issue by yozman** [GetuiLaboratory/cordova-plugin-getuisdk#15]
你好

我在通过 ionic2 来搭配个推实现手机端的推送

如何导入 `import GetuiSdkPlugin from 'xxx'`

该从哪里导入 `GetuiSdkPlugin` 呢？

**Comment by GetuiLab** [comment]
麻烦加下官网技术支持的qq



support@getui.com
 
发件人： 木由子
发送时间： 2016-11-10 13:24
收件人： GetuiLaboratory/cordova-plugin-getuisdk
主题： [GetuiLaboratory/cordova-plugin-getuisdk] ionic 从哪里 import GetuiSdkPlugin? (#15)
你好
我在通过 ionic2 来搭配个推实现手机端的推送
如何导入 import GetuiSdkPlugin from 'xxx'
该从哪里导入 GetuiSdkPlugin 呢？

**Comment by yozman** [comment]
找到解决方案了
第一种
添加 `declare var GeTuiSdkPlugin`

第二种
window['plugins'].GeTuiSdkPlugin

**Comment by mchenx** [comment]
请问你在ionic2中现在正常使用这个插件了吗？我最近也在开发，但发现这个插件好像有些问题，拿不到clientId （也就是在服务器上注册失败） @yozman
