### ISSUE TITLE
iOS安装出错

### ISSUE THREAD

**Issue by fenglu09** [GetuiLaboratory/cordova-plugin-getuisdk#16]
安装报错，`libGeTuiSdk-1.4.3.a ` 不存在。
希望作者可以将config.xml 里面的配置修改一下，改成对应的`libGeTuiSdk-1.5.0.a`
>  <source-file src="ios/GtSdkLib/libGeTuiSdk-1.5.0.a" framework="true"/>

PS：作为一个官方维护的个推插件，存在这种很无语的bug，对于个推这样的公司来说，的确不应该，值得反思。

**Comment by xbinglzh** [comment]
感谢您的反馈，问题已经修复。
