### ISSUE TITLE
是否需要 un-initialize ? 

### ISSUE THREAD

**Issue by xqyww123** [GetuiLaboratory/cordova-plugin-getuisdk#19]
安卓平台 物理返回按钮 退出程序后重新进入 个推被2次初始化，导致重复收到消息。

是否需要人工退出时 close 个推

或者在第二次启动是能否给予接口探测个推当前状态是否存活

**Comment by wutianjusouth** [comment]
您好，我们自测了一下，一定情况下确实存在该问题，目前正在排查和寻找合适的解决方案，下周会给解决的答复

**Comment by wutianjusouth** [comment]
您好，重复收到消息的问题我们现已查明原因并更新至GitHub，请下载最新版本，如有问题可同步。
