### ISSUE TITLE
我的Cordova app怎样才能获取通知的点击事件

### ISSUE THREAD

**Issue by ip192** [GetuiLaboratory/cordova-plugin-getuisdk#23]
我的项目里集成了这个sdk，现在遇到的问题时，手机上收到通知后，点击通知的后续事件要自己处理，但是我怎样才能获得通知的点击事件啊

**Comment by fenglu09** [comment]
这种情况需要发送透传消息，然后接收到消息后，再推送一条本地通知，在本地通知里面可以设置回调函数。本地通知的插件可以参考这个  [本地通知](https://github.com/katzer/cordova-plugin-local-notifications.git)

**Comment by ip192** [comment]
还有一个问题

**Comment by ip192** [comment]
还有一个问题，假如我的app已经退出后台了，那透传消息还能把数据送到吗

**Comment by fenglu09** [comment]
只要个推的推送服务进程还在，就可以收的到消息，但是这个时候，由于activity没有启动，js的回调是不会执行的。

**Comment by ip192** [comment]
那我要想在app退出后台时让app获得推送数据，就要先发一个消息把app唤醒，再发透传消息吗

**Comment by fenglu09** [comment]
不用啊，要收到消息的前提是，你的pushservice服务进程要在后台运行，如果没运行，是 收不到消息的。
如果pushservice在运行，但是app的activity并没有启动，也会走GeTuiSdkPushReceiver的onReceive方法，但是不会调用js的回调方法，因为cordovaWebViewReceiver 这个时候是null

**Comment by ip192** [comment]
谢了，看来个推的通知消息和透传消息没有一起使用的必要

**Comment by fenglu09** [comment]
这个肯定没必要一起使用，通知消息的话不好加事件处理。但是点击通知的话可以启动app。
透传消息，在我上面说的pushservice启动了，app没启动的情况下，就需要自己写android代码来实现通知了

**Comment by ip192** [comment]
抱歉我又来了，现在有这样一个需求，就是在应用退到后台，和正在前台使用这两种状态，能否通过透传数据，或者请求用户状态的方法得以区分？

**Comment by fenglu09** [comment]
这个可以实现啊，不过要写原生代码去判断了

**Comment by ip192** [comment]
这两天在接iOS端的时候，发现在app退到后台时，没有办法收到透传，我要在transmissionTemplate里加入payload属性吗，还是要用pushAPNMessageToSingle去推送，和android区别对待？

**Comment by fenglu09** [comment]
这个去看iOS的文档就可以了啊。
