### ISSUE TITLE
iOS透传消息，app在后台，收到消息，点击桌面的app图标，会调用GeTuiSdkDidReceivePayloadData方法。

### ISSUE THREAD

**Issue by fenglu09** [GetuiLaboratory/cordova-plugin-getuisdk#25]
现象： 当app在后台时，收到了透传消息，在没有点击通知栏的消息的情况下，点击桌面上的app图标，也会触发GeTuiSdkDidReceivePayloadData的回调。这点感觉很奇怪。如何在这种情况下，点击app图标后，不触发GeTuiSdkDidReceivePayloadData的回调呢？

**Comment by lin493369** [comment]
@fenglu09 当 App 在后台时，收到透传消息是离线消息，此时只要 App 启动，SDK 都会收到离线消息，因此是正常的。

**Comment by fenglu09** [comment]
嗯嗯，上午也问了个推的客服，他们解释了。
