### ISSUE TITLE
How to get devicetoken and send it to getui backend?

### ISSUE THREAD

**Issue by yuqitian** [GetuiLaboratory/cordova-plugin-getuisdk#26]
How to get devicetoken and send it to getui backend?

**Comment by fenglu09** [comment]
You should use native code to get devicetoken in `AppDelegate.m`
This is my code.
```objective-c
///** 远程通知注册成功委托 */
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    NSString *token = [[deviceToken description] stringByTrimmingCharactersInSet:[NSCharacterSet characterSetWithCharactersInString:@"<>"]];
    token = [token stringByReplacingOccurrencesOfString:@" " withString:@""];
    NSLog(@"\n>>>[DeviceToken Success]:%@\n\n", token);
    
    // [3]:向个推服务器注册deviceToken
    [GeTuiSdk registerDeviceToken:token];
}
```

**Comment by yuqitian** [comment]
我时用cordova跨平台方式开发的， 你上面那段 native 代码应该写在哪个文件中？  是写在  “GeTuiSdkPlugin.m” 这个文件中吗？

**Comment by fenglu09** [comment]
写在`AppDelegate.m`文件中

**Comment by mchenx** [comment]
我提的#30 是不是和这个有关？ 需要在AppDelegate.m中获取deviceToken并注册？

**Comment by fenglu09** [comment]
是的，这个的确和这个有关系。iOS的话需要你手动在AppDelegate.m中获取deviceToken并注册

**Comment by mchenx** [comment]
加如这段代码，就编译错误

The following build commands failed:

        CompileC /Users/zmci/Library/Developer/Xcode/DerivedData/zcom-fofshnrcgqxbovbmtcslegosxjok/Build/Intermediates/zcom-fofshnrcgqxbovbmtcslegosxjok/Build/Intermediates/zcom/Debug-iphonesimulator/zcom.build/Objects-normal/x86_64/AppDelegate.o zcom.build/Debug-iphonesimulator/zcom.build/Objects-normal/x86_64/AppDelegate.o zcom/Classes/AppDelegate.m normal x86
_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/mck/Projects/zmci/platforms/ios/cordova/build-deb
ug.xcconfig,-workspace,zcom.xcworkspace,-scheme,zcom,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 5s,build,CONFIGURATION_BUILD_DIR=/Users/zmci/Projects/zhongyi/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/zmci/Projects/zhongyi/platforms/ios/build/sharedpch

这是什么原因呢？我不大懂mac开发环境

**Comment by mchenx** [comment]
我用了你上面的代码 编译成功了  但是注册clientId 还是没有反应  也没报错

**Comment by fenglu09** [comment]
建议你看一下个推官网的iOS接入文档，那里有教程。

**Comment by mchenx** [comment]
这个插件不是直接能用的吗？ 还是需要自己在iOS二次开发？
我查了下 是需要 调registerForRemoteNotificationTypes 对吧？
