### ISSUE TITLE
Ionic2中无法使用

### ISSUE THREAD

**Issue by mchenx** [GetuiLaboratory/cordova-plugin-getuisdk#27]
我在ionic 2中导入了这个插件，callback的定义为：
function callback(type, data) {
    if(type == 'cid') {
        //TODO data = clientid
    } else if(type == 'pid') {
        //TODO data = 进程pid
    } else if(type == 'payload') {
    //TODO data=透传数据
    } else if(type == 'online') {
        if(data == 'true') {
            //TODO 已上线
        $('#clientid').text(clientid);
        } else {
            //TODO 已离线
        }
    }
};
调用以下代码后返回的type是pid  然后data是一个数字（进程id）, 我可以肯定的是appId是对的
GeTuiSdkPlugin.callback_init(callback);
GeTuiSdkPlugin.initialize();
调用GeTuiSdkPlugin.getVersion() 返回undefined
调用GeTuiSdkPlugin.turnOnPush() 没有任何反应
调用GeTuiSdkPlugin.() 没有任何反应
调用GeTuiSdkPlugin.turnOffPush()出现 ReferenceError: obj is not defined
调用GeTuiSdkPluggin.isPushTurnedOn()一直返回fasle

有谁在ionic或者ionic2上尝试过这个插件吗？

**Comment by wutianjusouth** [comment]
您好，可参考https://github.com/GetuiLaboratory/cordova-plugin-getuisdk/issues/15 ，有相关开发者采用了Ionic2 ，解决了相关的定义问题

**Comment by mchenx** [comment]
#15 是关于怎么使用GeTuiSdkPlugin的问题，这个我用的是全局变量，没什么问题。我遇到的问题是调用GeTuiSdkPlugin里面的function不起作用， 比如GeTuiSdkPlugin.initialize() 拿不到clientId。
我没有用plugman来安装这个插件  而是使用下面这个命令来安装的
ionic plugin add https://github.com/GetuiLaboratory/cordova-plugin-getuisdk --plugins_dir 你的插件目录 --variable PUSH_APPID=你的appid --variable PUSH_APPKEY=你的appkey --variable PUSH_APPSECRET=你的appsecret  
不知道是不是有关系，安装好插件后需要再install一下platform？

**Comment by wutianjusouth** [comment]
我们集成的方法是先安装platform，再安装插件，可能有影响，由于ionic2我们没有用过，所以具体的细节不是很清楚。

**Comment by mchenx** [comment]
> 调用以下代码后返回的type是pid 然后data是一个数字（进程id）, 我可以肯定的是appId是对的
> GeTuiSdkPlugin.callback_init(callback);
> GeTuiSdkPlugin.initialize();

initialize后 没有返回clientId而是返回进程id，这个是什么原因呢？

**Comment by wutianjusouth** [comment]
如果初始化成功，是既返回pid，也返回cid的，只返回pid的原因很可能就是初始化失败，应该是插件模块调用失败

**Comment by mchenx** [comment]
@wutianjusouth   谢谢！  找到原因了 之前添加插件时  --variable PUH_APPID的值写错了（最后多了个字母）   后来虽然在config.xml里面更正了，但是这个不起作用，需要删除插件重新添加 带上正确的appId
