### ISSUE TITLE
点击个推推送消息推后的事件是哪个？如何注册？可以传哪些参数？

### ISSUE THREAD

**Issue by mchenx** [GetuiLaboratory/cordova-plugin-getuisdk#28]
我使用Ionic2在开发app，希望在用户点击接收到的推送后做些处理，是否有这样的事件？是否可以在消息推送中添加按钮？

**Comment by Mickyxing** [comment]
你好。1.如果想对用户点击消息后的行为进行处理的话，可以推荐使用带透传的通知，每次用户点击消息后SDK会给JS传一个回调，具体的可以参考这个demo里面的第15行的回调处理https://github.com/GetuiLaboratory/cordova-plugin-getuisdk/blob/master/ios/demo/www/js/android_index.js
2.个推SDK中提供的消息样式中没有带按钮的通知栏，所以你这个需求可能需要通过自己发一个透传消息，然后在应用里接收透传后自己定义一个通知的方式进行展现
