### ISSUE TITLE
使用NotificationTemplate 进行推送，在应用关闭时，应用中推送不稳定

### ISSUE THREAD

**Issue by JoyceYy** [GetuiLaboratory/cordova-plugin-getuisdk#29]
NotificationTemplate 在应用关闭时，推送消息返回结果为发送成功，但是安卓应用中有时不显示，有时不显示推送，不稳定，大部分是直到打开应用，推送消息才显示，例子是拷贝官网的NotificationTemplate 的例子，设置setTransmissionType为1，请问大家又遇到这种不稳定的问题吗，怎么解决的呢？

**Comment by WcZhaoWei** [comment]
如遇到类似问题可以直接个推官网联系技术支持
