### ISSUE TITLE
iOS上getSdkwithAppId没有任何反应，没有错误信息

### ISSUE THREAD

**Issue by mchenx** [GetuiLaboratory/cordova-plugin-getuisdk#30]
如题

证书已上传

![image](https://cloud.githubusercontent.com/assets/1550186/23823085/6dadfdda-0695-11e7-8fe0-6fdef8737db6.png)

需要设置deviceToken吗？

**Comment by lin493369** [comment]
@mchenx 需要获取 deviceToken，才能测试，建议在 Xcode 中开启：
![image](https://cloud.githubusercontent.com/assets/8255169/23844904/0ad411b0-0800-11e7-8bcb-464f5c33e5cd.png)
只有开启该选项，才可以正确获取 deviceToken。
