### ISSUE TITLE
为什么我在phonegap build上编译时加载这个插件显示版本出现问题？

### ISSUE THREAD

**Issue by azraeljin** [GetuiLaboratory/cordova-plugin-getuisdk#33]
Error - The following plugin, plugin version or a dependancy of this plugin is not on npm: cordova-plugin-getuisdk@1.0.0下面是我在config.xml中安装的插件，密码已经抹去，不是密码问题。<plugin name="cordova-plugin-getuisdk"version="1.0.0"src="https://github.com/GetuiLaboratory/cordova-plugin-getuisdk"> </plugin>

**Comment by BigMuGe** [comment]
npm命令是不能直接安装插件的，需要使用cordova命令安装

**Comment by azraeljin** [comment]
这个是在线编译的 好像不能输入cordova命令。
