### ISSUE TITLE
ios使用时候提示错误， “ramework not found UserNotifications”

### ISSUE THREAD

**Issue by MinzhangWei** [GetuiLaboratory/cordova-plugin-getuisdk#41]
![Uploading image.png…]()

这个是怎么解决的呢

**Comment by lin493369** [comment]
图片没有显示出来。
在 iOS 工程中，选择项目 Target->Build phases->Link Binary With Libararies ，添加 UserNotification.framework 并设置为 optional .
![image](https://cloud.githubusercontent.com/assets/8255169/24577228/80cd1866-16fc-11e7-9a55-7e96be95e939.png)

**Comment by MinzhangWei** [comment]
谢谢，这个是因为xcode版本的问题，需要xcode 8.0以上。
