### ISSUE TITLE
编译不通过，报错

### ISSUE THREAD

**Issue by Jam1zhu** [GetuiLaboratory/cordova-plugin-getuisdk#51]
编译报错，不会原生，求大神指点
jdk:1.8
corodva:7.01

```java
:transformClassesWithDexForDebug
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
 FAILED

BUILD FAILED

Total time: 7.088 secs
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /Users/ZLY/project/hato/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/ZLY/project/hato/app/platforms/android/src/cn/jiguang/cordova/push/JPushPlugin.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by GetuiLab** [comment]
麻烦加下官网技术支持的请求，在qq里比较方便沟通！！


support@getui.com
 
发件人： Jam1zhu
发送时间： 2017-10-10 16:14
收件人： GetuiLaboratory/cordova-plugin-getuisdk
抄送： Subscribed
主题： [GetuiLaboratory/cordova-plugin-getuisdk] 编译不通过，报错 (#51)
编译报错，不会原生，求大神指点
jdk:1.8
corodva:7.01
:transformClassesWithDexForDebug
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
 FAILED
BUILD FAILED
Total time: 7.088 secs
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /Users/ZLY/project/hato/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/ZLY/project/hato/app/platforms/android/src/cn/jiguang/cordova/push/JPushPlugin.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by pfdgithub** [comment]
@Jam1zhu 
问题解决了吗？

@GetuiLab 
即时通讯软件不适合用来处理累死问题，因为问题的解决方案无法沉淀下来。
不便于搜索引擎抓去，每个人都要加群重新提问，不利于个推的社区推广。

**Comment by GetuiLab** [comment]
hi，抱歉，个推这边不知道是否能提供什么帮助。
目前是github这边对应个推有什么特殊处理还是？



support@getui.com
 
发件人： pfdgithub
发送时间： 2017-10-11 09:34
收件人： GetuiLaboratory/cordova-plugin-getuisdk
抄送： GetuiLab; Mention
主题： Re: [GetuiLaboratory/cordova-plugin-getuisdk] 编译不通过，报错 (#51)
我的决绝方案如下，可以参考一下：
安装个推插件后，编译时出现错误：
Execution failed for task ':transformClassesWithDexForDebug'
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

需要删除 plugins/cordova-plugin-getuisdk/plugin.xml 中的 android-support-v4.jar 引用。
<source-file src="android/GtSdkLib/android-support-v4.jar" target-dir="libs"/>

并删除 platforms/android/libs//android-support-v4.jar 文件。
