### ISSUE TITLE
android别名问题

### ISSUE THREAD

**Issue by cnryb** [GetuiLaboratory/cordova-plugin-getuisdk#52]
当Android的时候，如果别名中存在短横线，也就是这个字符 `-` 
callback 返回的值是 true。
但是在个推别名管理中并不能查询到绑定成功的记录。

当查询文档的时候才发现，别名的规则 
`长度40字节，支持中、英文（区分大小写）、数字以及下划线 `

**为了更方便使用，能否在别名中出现异常字符的时候，直接给与提示呢？**

**另外在什么时候绑定别名会比较合适？**

详细问题见下面代码片段中绑定别名前注释部分

function callback(type, data) {
        console.log(type);
	if(type == 'cid') {
		//TODO data = clientid
	} else if(type == 'pid') {
		//TODO data = 进程pid
	} else if(type == 'payload') {
   		//TODO data=透传数据
	} else if(type == 'online') {
		if(data == 'true') {
			//TODO 已上线
		} else {
			//TODO 已离线
		}
	}
};
   GeTuiSdkPlugin.callback_init(callback);
   GeTuiSdkPlugin.initialize();

   //如果绑定别名写到这里，上面写的callback仅触发一次。然后下面的程序就会打印 true 了。
  //如果先注释掉下面的绑定别名，上面的 callback 会触发三次， 控制台打印顺序 pid，cid，online
    GeTuiSdkPlugin.bindAlias(function (type, data) {
        console.log(type);
        console.log(data);
    }, 'android_' + g_account.userId);

  
测试程序地址，使用开发工具vs2017
[https://github.com/cnryb/CordovaTest/tree/master/PushTest](https://github.com/cnryb/CordovaTest/tree/master/PushTest)

**Comment by GetuiLab** [comment]
麻烦加下官网首页技术支持的qq！



support@getui.com
 
发件人： 任跃兵
发送时间： 2018-01-08 14:06
收件人： GetuiLaboratory/cordova-plugin-getuisdk
抄送： Subscribed
主题： [GetuiLaboratory/cordova-plugin-getuisdk] android别名问题 (#52)
当Android的时候，如果别名中存在短横线，也就是这个字符 -
callback 返回的值是 true。
但是在个推别名管理中并不能查询到绑定成功的记录。
当查询文档的时候才发现，别名的规则
长度40字节，支持中、英文（区分大小写）、数字以及下划线
为了更方便使用，能否在别名中出现异常字符的时候，直接给与提示呢？
另外在什么时候绑定别名会比较合适？
详细问题见下面代码片段中绑定别名前注释部分
function callback(type, data) {
console.log(type);
if(type == 'cid') {
//TODO data = clientid
} else if(type == 'pid') {
//TODO data = 进程pid
} else if(type == 'payload') {
//TODO data=透传数据
} else if(type == 'online') {
if(data == 'true') {
//TODO 已上线
} else {
//TODO 已离线
}
}
};
GeTuiSdkPlugin.callback_init(callback);
GeTuiSdkPlugin.initialize();
//如果绑定别名写到这里，上面写的callback仅触发一次。然后下面的程序就会打印 true 了。
//如果先注释掉下面的绑定别名，上面的 callback 会触发三次， 控制台打印顺序 pid，cid，online
GeTuiSdkPlugin.bindAlias(function (type, data) {
console.log(type);
console.log(data);
}, 'android_' + g_account.userId);
