### ISSUE TITLE
打包报gradle错

### ISSUE THREAD

**Issue by Jackenen** [GetuiLaboratory/cordova-plugin-getuisdk#53]
按照文档，在MainActivity中导入GeTuiSdkPlugin类，初始化插件后，按正常流程打包报gradle错是什么鬼？有遇到的大神么？这样导的import com.igexin.getui.phonegap.GeTuiSdkPlugin;

**Comment by GetuiLab** [comment]
您好，麻烦加下官网首页技术支持的qq，详细沟通下您的问题



support@getui.com
 
发件人： Jackenen
发送时间： 2018-04-12 15:10
收件人： GetuiLaboratory/cordova-plugin-getuisdk
抄送： Subscribed
主题： [GetuiLaboratory/cordova-plugin-getuisdk] 打包报gradle错 (#53)
按照文档，在MainActivity中导入GeTuiSdkPlugin类，初始化插件后，按正常流程打包报gradle错是什么鬼？有遇到的大神么？这样导的import com.igexin.getui.phonegap.GeTuiSdkPlugin;
