### ISSUE TITLE
back内容是啥？？？

### ISSUE THREAD

**Issue by Jackenen** [GetuiLaboratory/cordova-plugin-getuisdk#54]
下面两个方法中back内容是啥？？？好奇怪的样子
function getCID(back){
	GeTuiSdkPlugin.getClientId(back);
}

function getVersion(back){
	GeTuiSdkPlugin.getVersion(back);
}

**Comment by GetuiLab** [comment]
您好，麻烦您加下官网首页技术支持的qq，详细沟通下您的问题！！



support@getui.com
 
发件人： Jackenen
发送时间： 2018-04-12 17:19
收件人： GetuiLaboratory/cordova-plugin-getuisdk
抄送： Subscribed
主题： [GetuiLaboratory/cordova-plugin-getuisdk] back内容是啥？？？ (#54)
下面两个方法中back内容是啥？？？好奇怪的样子
function getCID(back){
GeTuiSdkPlugin.getClientId(back);
}
function getVersion(back){
GeTuiSdkPlugin.getVersion(back);
}
