### ISSUE TITLE
cordova-android 7.0.0/7.1.0的支持

### ISSUE THREAD

**Issue by mchenx** [GetuiLaboratory/cordova-plugin-getuisdk#56]
目前的插件不支持cordova-android@7.0.0或者更高版本，近期有更新的计划吗？

**Comment by mchenx** [comment]
还是没计划吗？哎~ 不行就换别的服务了

**Comment by WcZhaoWei** [comment]
您好，有兼容方法的，需要自己修改，[Cordova Android 7.0.0 Released!](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html)
