### ISSUE TITLE
iOS透传消息返回回调 GeTuiSdk.retrievePayloadById is not a function

### ISSUE THREAD

**Issue by fenglu09** [GetuiLaboratory/cordova-plugin-getuisdk#8]
iOS平台中，按照文档上面说的配置透传消息的回调，

![qq20160718-0](https://cloud.githubusercontent.com/assets/12250129/16914186/c29a1b58-4d22-11e6-9ac5-a50941896443.png)

@xbinglzh  @xiangzilv123 @a200210313 @GetuiLab 

但是在使用的时候，出现下面的错误：
```
GeTuiSdk.retrievePayloadById is not a function. (In  GeTuiSdk.retrievePayloadById(retrievePayloadByIdCallback, payloadId)', 'GeTuiSdk.retrievePayloadById' is undefined)
```

而且在iOS插件的  [`GetuiSdk.js`](https://github.com/GetuiLaboratory/cordova-plugin-getuisdk/blob/master/ios/www/GeTuiSdk.js) 的文件里面也没有找到`retrievePayloadById` 这个方法.

是插件的问题还是文档没有更新？？

**Comment by fenglu09** [comment]
提交[＃9](https://github.com/GetuiLaboratory/cordova-plugin-getuisdk/pull/9) 已解决

**Comment by xbinglzh** [comment]
你好 ，插件 已经更新了。 更新下 修复了这个问题。
